PythonVersion="3.7.9"
virtualEnvName="antenv"
compressedVirtualEnvFile="antenv.tar.gz"
OperationId="|sBjKXNh6rCQ=.70598e2a_"
SourceDirectoryInBuildContainer="/tmp/8d8ca632a6bd74f"
PlatformName="python"
CompressDestinationDir="false"
