from openpyxl import Workbook, load_workbook
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException
from lxml import html
import os
from pywinauto.application import Application as app
from pywinauto import mouse as mouse1, keyboard
import time
from random import randrange

from datetime import datetime
import mouse


# left click


# app.menu_select('menu->Open Dashboard')
# Hubstaff.Hubstaff.menu_select('Open Dashboard')
# mouse.move(-200, 200, absolute=False, duration=0.2)
# mouse.click('left')


executable_path = r'C:\Users\ramyg\Downloads\chromedriver_win32 (1)\chromedriver.exe'
os.environ['webdriver.chrome.driver'] = executable_path
chrome_options = Options()
chrome_options.add_argument('--disable-blink-features=AutomationControlled')
chrome_options.add_argument('start-maximized')
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option('useAutomationExtension', False)
driver = webdriver.Chrome(options=chrome_options, executable_path=executable_path)
driver.get('http://shops.syaanh.com/login')

driver.find_element_by_xpath('//*[@id="email"]').send_keys('ramy.zaghloul@mzadqatar.com')
driver.find_element_by_xpath('//*[@id="password"]').send_keys('BDZuKtqUwaL2b3fd')
driver.find_element_by_xpath('//*[@id="app"]/main/div/div/div/div/div[2]/form/div[4]/div/button').click()
driver.get('http://shops.syaanh.com/admin/default/jqadm/search/product?lang=en')

time.sleep(3)

# driver.switch_to.window(driver.window_handles[0])
driver.execute_script("window.open('about:blank', 'tab2');")
driver.switch_to.window("tab2")
driver.get('https://ebdaadt.atlassian.net/browse/CON-109')
driver.find_element_by_xpath('//*[@id="username"]').send_keys('ramy.zaghloul@mzadqatar.com')
driver.find_element_by_xpath('//*[@id="login-submit"]/span/span').click()
time.sleep(1)
driver.find_element_by_xpath('//*[@id="password"]').send_keys('RAmy@@1991')
time.sleep(1)
driver.find_element_by_xpath('//*[@id="login-submit"]/span/span').click()
time.sleep(3)
driver.get('https://ebdaadt.atlassian.net/browse/CON-21')

# driver.get(
#     'https://aid-frontend.prod.atl-paas.net/atlassian-id/front-end/5.0.224')

driver.execute_script("window.open('about:blank', 'tab3');")
driver.switch_to.window("tab3")
driver.get('https://ebdaadt.slack.com/')
time.sleep(2)
driver.find_element_by_xpath('//*[@id="email"]').send_keys('ramy.zaghloul@mzadqatar.com')
driver.find_element_by_xpath('//*[@id="password"]').send_keys('Pass@@1991')
driver.find_element_by_xpath('//*[@id="signin_btn"]').click()
time.sleep(3)

link = driver.find_element_by_xpath('//*[@id="page_contents"]/div/div/div[2]/p/a').get_attribute('href')
driver.get(link)
time.sleep(1)
driver.get('https://app.slack.com/client/T8N1GPQS1/D01T8951LLS')

driver.execute_script("window.open('about:blank', 'tab4');")
driver.switch_to.window("tab4")
driver.get(
    'https://mzad.awsapps.com/auth/?client_id=6b9615ec01be1c8d&redirect_uri=https%3A%2F%2Fwebmail.mail.us-east-1.awsapps.com%2Fworkmail%2F')
time.sleep(5)
driver.find_element_by_xpath('//*[@id="wdc_username"]').send_keys('ramy.zaghloul')
driver.find_element_by_xpath('//*[@id="wdc_password"]').send_keys('Pass@@1991')
driver.find_element_by_xpath('//*[@id="wdc_login_button"]').click()

driver.execute_script("window.open('about:blank', 'tab5');")
driver.switch_to.window("tab5")

driver.get('https://docs.google.com/spreadsheets/d/1jFuSRtZYkx02XTVOZltnBKtrXGbGAlPHhgBPwMSgs2Y/edit#gid=420486138')
driver.execute_script("window.open('about:blank', 'tab6');")

driver.switch_to.window("tab6")
driver.get('https://docs.google.com/spreadsheets/d/1LTyaf2EtFO08BN8cunbPEgNSfZ-zQJsWQMfnBfEKUII/edit#gid=22035314')
tab = ['tab2', 'tab3', 'tab4', 'tab5', 'tab6']

app = app().start(r"C:\Program Files\Hubstaff\HubstaffClient.exe")
mouse1.click(button='left', coords=(1698, 353))
mouse1.click(button='left', coords=(1772, 150))
print(randrange(3))
while True:
    # chrome
    mouse1.click(button='left', coords=(852, 1060))
    time.sleep(1 + randrange(3))
    mouse1.move(coords=(640, 500))
    time.sleep(1)
    mouse1.scroll(coords=(640, 500), wheel_dist=1)
    time.sleep(1)
    mouse1.scroll(coords=(700, 600), wheel_dist=2)
    time.sleep(1 + randrange(3))
    mouse1.scroll(coords=(500, 400), wheel_dist=1)
    time.sleep(1 + randrange(6))
    mouse1.scroll(coords=(400, 650), wheel_dist=3)
    time.sleep(1)
    mouse1.scroll(coords=(400, 650), wheel_dist=-9)
    time.sleep(2 + randrange(4))
    # sublime
    mouse1.click(button='left', coords=(852, 1060))
    time.sleep(2 + randrange(4))
    mouse1.click(button='left', coords=(400, 20))
    time.sleep(1)
    mouse1.move(coords=(780, 680))
    mouse1.scroll(coords=(780, 680), wheel_dist=5)
    time.sleep(1)
    mouse1.click(button='left', coords=(660, 867))
    time.sleep(2 + randrange(3))
    keyboard.send_keys('^a^c')
    mouse1.move(coords=(963, 18))
    time.sleep(4)
    # Excel
    mouse1.move(coords=(665, 1061))
    time.sleep(1)
    mouse1.click(button='left', coords=(665, 1061))
    mouse1.move(coords=(1400, 526))
    mouse1.move(coords=(143, 700))
    mouse1.move(coords=(645, 1453))
    mouse1.move(coords=(645, 456))
    mouse1.move(coords=(545, 585))
    mouse1.move(coords=(1400, 400))
    time.sleep(1)
    mouse1.click(button='left', coords=(1402, 527))
    time.sleep(2)
    mouse1.move(coords=(111, 666))
    mouse1.move(coords=(925, 527))
    mouse1.click(button='right', coords=(925, 527))
    time.sleep(randrange(4))
    mouse1.click(button='left', coords=(900, 502))
    time.sleep(2)
    mouse1.click(button='left', coords=(923, 525))
    time.sleep(3 + randrange(2))
    mouse1.move(coords=(213, 355))
    mouse1.move(coords=(410, 527))
    time.sleep(1)
    mouse1.click(button='left', coords=(410, 527))
    time.sleep(3 + randrange(3))
    mouse1.move(coords=(852, 1060))
    time.sleep(1 + randrange(3))
    # folder
    mouse1.click(button='left', coords=(420, 1060))
    mouse1.click(button='left', coords=(290, 209))
    mouse1.click(button='left', coords=(418, 219))
    mouse1.click(button='left', coords=(567, 209))
    mouse1.click(button='left', coords=(567, 209))
    mouse1.click(button='left', coords=(709, 215))
    mouse1.click(button='left', coords=(820, 210))
    mouse1.move(coords=(713, 673))
    mouse1.click(button='left', coords=(713, 673))
    mouse1.click(button='left', coords=(713, 673))
    mouse1.click(button='left', coords=(713, 673))
    mouse1.click(button='left', coords=(845, 704))
    mouse1.move(coords=(1500, 704))
    mouse1.move(coords=(1000, 804))
    mouse1.move(coords=(500, 500))
    mouse1.move(coords=(123, 877))
    mouse1.move(coords=(32, 657))
    mouse1.move(coords=(435, 321))
    mouse1.move(coords=(231, 123))
    mouse1.move(coords=(12, 234))
    mouse1.move(coords=(435, 965))
    mouse1.move(coords=(343, 123))
    mouse1.move(coords=(13, 87))
    mouse1.move(coords=(654, 12))
    mouse1.move(coords=(533, 124))
    mouse1.move(coords=(868, 123))
    mouse1.move(coords=(543, 978))
    mouse1.move(coords=(400, 600))
    mouse1.click(button='right', coords=(1128, 712))
    time.sleep(randrange(3))
    mouse1.click(button='left', coords=(1044, 666))
    time.sleep(randrange(3))
    # chrome
    mouse1.click(button='left', coords=(852, 1060))
    time.sleep(2)
    mouse1.move(coords=(1017, 20))
    time.sleep(1)
    mouse1.move(coords=(1240, 21))
    mouse1.click(button='left', coords=(1240, 21))
    time.sleep(1 + randrange(3))
    mouse1.move(coords=(1905, 450))
    mouse1.scroll(coords=(1906, 451), wheel_dist=4)
    mouse1.scroll(coords=(1906, 451), wheel_dist=-6)
    mouse1.scroll(coords=(1903, 449), wheel_dist=5)
    mouse1.move(coords=(456, 433))
    mouse1.move(coords=(345, 450))
    mouse1.move(coords=(124, 232))
    time.sleep(1 + randrange(3))
    mouse1.move(coords=(408, 504))
    time.sleep(1)
    driver.switch_to.window("tab2")
    time.sleep(2 + randrange(3))
    mouse1.move(coords=(700, 900))
    time.sleep(1)
    driver.switch_to.window("tab3")
    mouse1.scroll(coords=(1645, 450), wheel_dist=8)
    mouse1.scroll(coords=(1645, 655), wheel_dist=-8)
    time.sleep(3 + randrange(3))
    driver.switch_to.window("tab4")
    time.sleep(2 + randrange(3))
    driver.switch_to.window("tab5")
    time.sleep(0.2 + randrange(3))
    driver.switch_to.window("tab6")
    mouse1.scroll(coords=(1700, 700), wheel_dist=1)
    time.sleep(3)
    mouse1.move(coords=(250, 700))
    mouse1.scroll(coords=(1705, 690), wheel_dist=-1)
    time.sleep(randrange(4))
    mouse1.scroll(coords=(1500, 600), wheel_dist=1)
    mouse1.move(coords=(300, 500))
    driver.switch_to.window(driver.window_handles[0])
    time.sleep(randrange(3))
    # mouse1.click(button='left', coords=(50, 580))
    mouse1.scroll(coords=(1705, 690), wheel_dist=4)
    time.sleep(randrange(4))
    mouse1.scroll(coords=(1500, 600), wheel_dist=-3)
    time.sleep(2 + randrange(3))
    mouse1.click(button='left', coords=(295, 1050))
    mouse1.move(coords=(270, 1340))
    mouse1.move(coords=(27, 340))
    time.sleep(randrange(3))
    mouse1.click(button='left', coords=(27, 340))
    mouse1.move(coords=(1195, 660))
    time.sleep(4 + randrange(3))
    mouse1.scroll(coords=(1180, 650), wheel_dist=1)
    mouse1.scroll(coords=(1190, 690), wheel_dist=1)
    mouse1.scroll(coords=(1197, 700), wheel_dist=1)
    mouse1.scroll(coords=(1200, 660), wheel_dist=1)
    mouse1.scroll(coords=(1200, 789), wheel_dist=1)
    mouse1.scroll(coords=(1200, 660), wheel_dist=2)
    mouse1.scroll(coords=(1200, 675), wheel_dist=1)
    mouse1.scroll(coords=(1200, 756), wheel_dist=-8)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # # mouse.click('left')
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # driver.switch_to.window("tab2")
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # # mouse.click('left')
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # driver.switch_to.window("tab3")
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # mouse.click('left')
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # driver.switch_to.window("tab4")
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # # mouse.click('left')
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # # mouse.click('left')
    # driver.switch_to.window("tab5")
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # mouse.click('left')
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # # mouse.click('left')
    # driver.switch_to.window("tab6")
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(2)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(100, -100, absolute=False, duration=0.2)
    # time.sleep(1)
    # mouse.move(-100, 100, absolute=False, duration=0.2)
    # mouse.click('left')
    # driver.switch_to.window(driver.window_handles[0])
