items = [('B099SCWZ2F', 'www.amazon.eg', 'A2dbd27c2', 'eg',
          '{"EGP": {"25-05-2022_22:39:01": {"date_time": "25-05-2022 22:39:01", "price": 340.0, "currency": "EGP"}}}',
          '', '', '', '', 'test',
          'The Official Guide to the TOEFL Test with DVD - ROM, Fifth Edition, Ed.5 By Educational Testing Service',
          'The Official Guide to the TOEFL Test with DVD - ROM, Fifth Edition, Ed.5 By Educational Testing Service',
          'by Educational Testing Service (Author)', 'by Educational Testing Service (Author)', '', '',
          'https://images-na.ssl-images-amazon.com/images/I/51+-hrpDe3S._AC_SL1500_.jpg',
          'https://www.amazon.eg/dp/B099SCWZ2F/?language=en_AE', 'https://www.amazon.eg/dp/B099SCWZ2F/?language=en_AE',
          '', 0, 0, 0, '22-05-25'), ('B07L5GZ6J6', 'www.amazon.eg', 'Aaf535ed4', 'eg',
                                     '{"EGP": {"25-05-2022_22:39:01": {"date_time": "25-05-2022 22:39:01", "price": 120.0, "currency": "EGP"}}}',
                                     '', '', '', '', 'test', 'Gluco Dr Auto Test Strips', 'Gluco Dr Auto Test Strips',
                                     'Gluco Dr', 'Gluco Dr', '', '',
                                     'https://images-na.ssl-images-amazon.com/images/I/31FL0DqFHhL._AC_SL1500_.jpg',
                                     'https://www.amazon.eg/dp/B07L5GZ6J6/?language=en_AE',
                                     'https://www.amazon.eg/dp/B07L5GZ6J6/?language=en_AE', '', 0, 0, 0, '22-05-25'), (
             'B07NBQ1YLX', 'www.amazon.eg', 'Ae8721d9d', 'eg',
             '{"EGP": {"25-05-2022_22:39:01": {"date_time": "25-05-2022 22:39:01", "price": 50.0, "currency": "EGP"}}}',
             '',
             '', '', '', 'test', 'OVULA Ultra Early Pregnancy Test Ovola Pregnancy Test',
             'OVULA Ultra Early Pregnancy Test Ovola Pregnancy Test', 'Generic', 'Generic', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41TMBOLd3ZL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B07NBQ1YLX/?language=en_AE',
             'https://www.amazon.eg/dp/B07NBQ1YLX/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B00AOJ5R8W', 'www.amazon.eg', 'Ab3d90f34', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:01": {"date_time": "25-05-2022 22:39:01", "price": 2149.0, "currency": "EGP"}}}',
                                        '', '', '', '', 'test', 'Clearblue Advanced Digital Ovulation Test, 20 Count',
                                        'Clearblue Advanced Digital Ovulation Test, 20 Count', 'Clearblue', 'Clearblue',
                                        '',
                                        '', 'https://m.media-amazon.com/images/I/71ltH+TC-JL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B00AOJ5R8W/?language=en_AE',
                                        'https://www.amazon.eg/dp/B00AOJ5R8W/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B091JNCLGD', 'www.amazon.eg', 'A6a9439d8', 'eg',
             '{"EGP": {"25-05-2022_22:39:01": {"date_time": "25-05-2022 22:39:01", "price": 350.0, "currency": "EGP"}}}',
             'Measuring & Layout', 'Measuring & Layout', 'Measuring & Layout', 'Measuring & Layout', 'test',
             'Pool Water Test Kit (Chlorine & Ph) With Carry Case TK-01',
             'Pool Water Test Kit (Chlorine & Ph) With Carry Case TK-01', 'Hengbo', 'Hengbo', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/6167iXHMIfL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B091JNCLGD/?language=en_AE',
             'https://www.amazon.eg/dp/B091JNCLGD/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B093QFBQ16', 'www.amazon.eg', 'A8448ca37', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 169.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test',
                                        'Fine Test Blood Glucose Test Strips, 50 Strips',
                                        'Fine Test Blood Glucose Test Strips, 50 Strips', 'Fine Test', 'Fine Test', '',
                                        '',
                                        'https://images-na.ssl-images-amazon.com/images/I/61l9ajYEz5S._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B093QFBQ16/?language=en_AE',
                                        'https://www.amazon.eg/dp/B093QFBQ16/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B0966S5FRH', 'www.amazon.eg', 'A65aed010', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 85.0, "currency": "EGP"}}}',
             'Power Screwdrivers', 'Power Screwdrivers', 'Power Screwdrivers', 'Power Screwdrivers', 'test',
             'DURMIRI Test Digital Screwdriver', 'DURMIRI Test Digital Screwdriver', 'DURMIRI', 'DURMIRI', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/51JgtA-npkS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B0966S5FRH/?language=en_AE',
             'https://www.amazon.eg/dp/B0966S5FRH/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B0968WT1BW', 'www.amazon.eg', 'Aa97dbc29', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 125.0, "currency": "EGP"}}}',
                                        'Measuring & Layout', 'Measuring & Layout', 'Measuring & Layout',
                                        'Measuring & Layout', 'test', 'OF PH Test Strips, Range 0-14. Pack of 100',
                                        'OF PH Test Strips, Range 0-14. Pack of 100', 'OF', 'OF', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/71A258QbNJS._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B0968WT1BW/?language=en_AE',
                                        'https://www.amazon.eg/dp/B0968WT1BW/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B08YNCV5B1', 'www.amazon.eg', 'Af5e1fed5', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 109.0, "currency": "EGP"}}}',
             'Electrical Tools & Testers', 'Electrical Tools & Testers', 'Electrical Tools & Testers',
             'Electrical Tools & Testers', 'test', 'Digital Multimeter - DT9205A', 'Digital Multimeter - DT9205A',
             'Generic', 'Generic', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41I7ga1b6bL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B08YNCV5B1/?language=en_AE',
             'https://www.amazon.eg/dp/B08YNCV5B1/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B085VHMFL4', 'www.amazon.eg', 'A62c1bd33', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 195.0, "currency": "EGP"}}}',
                                        'Lab Tubes', 'Lab Tubes', 'Lab Tubes', 'Lab Tubes', 'test',
                                        'SCSpecial Plastic Test Tubes with Caps 30 Pieces 10 Milliliters Laboratory Tubes for Scientific Experiments Clear Testing Tubes for Halloween',
                                        'SCSpecial Plastic Test Tubes with Caps 30 Pieces 10 Milliliters Laboratory Tubes for Scientific Experiments Clear Testing Tubes for Halloween',
                                        'SCSpecial', 'SCSpecial', '', '',
                                        'https://m.media-amazon.com/images/I/61H+u9z1dtL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B085VHMFL4/?language=en_AE',
                                        'https://www.amazon.eg/dp/B085VHMFL4/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B09KYD67PS', 'www.amazon.eg', 'Af2c16806', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 5750.0, "currency": "EGP"}}}',
             'Binoculars', 'Binoculars', 'Binoculars', 'Binoculars', 'test',
             'Microscope Digital Microscope Blood Biological Test 9-Inch LCD Screen Digital Simple Version',
             'Microscope Digital Microscope Blood Biological Test 9-Inch LCD Screen Digital Simple Version', 'Generic',
             'Generic', '', '', 'https://images-na.ssl-images-amazon.com/images/I/418cBmOpNrL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B09KYD67PS/?language=en_AE',
             'https://www.amazon.eg/dp/B09KYD67PS/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09816LYTT', 'www.amazon.eg', 'A76047dce', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 65.0, "currency": "EGP"}}}',
                                        "Socks & Hosiery @ Socks @ Boys' Socks",
                                        "Socks & Hosiery @ Socks @ Boys' Socks",
                                        "Boys' Socks", "Boys' Socks", 'test', 'DIAN GONG Electronic Test Screwdriver',
                                        'DIAN GONG Electronic Test Screwdriver', 'DIAN GONG', 'DIAN GONG', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/516qW342oPS._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09816LYTT/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09816LYTT/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B099P4MR4R', 'www.amazon.eg', 'Ae469d2ed', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 145.0, "currency": "EGP"}}}',
             '', '', '', '', 'test', 'Gluco Dr Fine Test Blood Glucose Monitor',
             'Gluco Dr Fine Test Blood Glucose Monitor',
             'Gluco Dr', 'Gluco Dr', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/71dHU8yTRCS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B099P4MR4R/?language=en_AE',
             'https://www.amazon.eg/dp/B099P4MR4R/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B093QGQWSN', 'www.amazon.eg', 'A631bdb5d', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 189.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test',
                                        'Element Blood Glucose Test Strips, 50 Strips',
                                        'Element Blood Glucose Test Strips, 50 Strips', 'ELEMENT', 'ELEMENT', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/41diMQnzxuS._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B093QGQWSN/?language=en_AE',
                                        'https://www.amazon.eg/dp/B093QGQWSN/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B09G2M2ZKY', 'www.amazon.eg', 'A32f93b34', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 584.0, "currency": "EGP"}}}',
             '', '', '', '', 'test', 'Accu-Chek Sugar Meter Monitoring System with 50 Test Strips',
             'Accu-Chek Sugar Meter Monitoring System with 50 Test Strips', 'Generic', 'Generic', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41cxfTUML9L._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B09G2M2ZKY/?language=en_AE',
             'https://www.amazon.eg/dp/B09G2M2ZKY/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09JMH7LPK', 'www.amazon.eg', 'A70c2772e', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 175.0, "currency": "EGP"}}}',
                                        '', '', '', '', 'test', 'Smart Test Blood Glucose Strips - 50 Strips',
                                        'Smart Test Blood Glucose Strips - 50 Strips', 'Smart Test', 'Smart Test', '',
                                        '',
                                        'https://images-na.ssl-images-amazon.com/images/I/41gvixwbRbL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09JMH7LPK/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09JMH7LPK/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B098WC3Q63', 'www.amazon.eg', 'A655661d5', 'eg',
             '{"EGP": {"25-05-2022_22:39:02": {"date_time": "25-05-2022 22:39:02", "price": 13.0, "currency": "EGP"}}}',
             'Automotive Diagnostic, Test & Measuring Tools', 'Automotive Diagnostic, Test & Measuring Tools',
             'Automotive Diagnostic, Test & Measuring Tools', 'Automotive Diagnostic, Test & Measuring Tools', 'test',
             'Total Test Pencil THT291908', 'Total Test Pencil THT291908', 'Generic', 'Generic', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41pCNIsHGbS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B098WC3Q63/?language=en_AE',
             'https://www.amazon.eg/dp/B098WC3Q63/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09NQ1FM1Z', 'www.amazon.eg', 'A22880d15', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 38.0, "currency": "EGP"}}}',
                                        '', '', '', '', 'test',
                                        'Sure Check Pregnancy Test - Accurate at All Time 1 Test',
                                        'Sure Check Pregnancy Test - Accurate at All Time 1 Test', 'Generic', 'Generic',
                                        '',
                                        '',
                                        'https://images-na.ssl-images-amazon.com/images/I/51ZBkxY2moL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09NQ1FM1Z/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09NQ1FM1Z/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B09QSPKJYD', 'www.amazon.eg', 'A06b124ee', 'eg',
             '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 62.0, "currency": "EGP"}}}',
             'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'test',
             'Tester Network ROHS Test) High Quality', 'Tester Network ROHS Test) High Quality', 'Other', 'Other', '',
             '',
             'https://m.media-amazon.com/images/I/513+JNjnkHL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B09QSPKJYD/?language=en_AE',
             'https://www.amazon.eg/dp/B09QSPKJYD/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09KS29T66', 'www.amazon.eg', 'A37a01c83', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 400.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test', 'CONTOUR TS Meter (50 Test Strips)',
                                        'CONTOUR TS Meter (50 Test Strips)', 'CONTOUR TS', 'CONTOUR TS', '', '',
                                        'https://m.media-amazon.com/images/I/61U7558+KfL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09KS29T66/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09KS29T66/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B07ZJFD5JX', 'www.amazon.eg', 'Ace9a4a65', 'eg',
             '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 101.0, "currency": "EGP"}}}',
             'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'test',
             'Vixzero DC 6V/12V/24V Auto Truck Car Electrical Circuit Continuity Tester Test Light Pen Tool with Indicator Light',
             'Vixzero DC 6V/12V/24V Auto Truck Car Electrical Circuit Continuity Tester Test Light Pen Tool with Indicator Light',
             'Vixzero', 'Vixzero', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41nPpcPJdjL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B07ZJFD5JX/?language=en_AE',
             'https://www.amazon.eg/dp/B07ZJFD5JX/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B07N5ZQWQ6', 'www.amazon.eg', 'Ae02459df', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 273.0, "currency": "EGP"}}}',
                                        'Monitors @ Blood Pressure Monitors & Accessories',
                                        'Monitors @ Blood Pressure Monitors & Accessories',
                                        'Blood Pressure Monitors & Accessories',
                                        'Blood Pressure Monitors & Accessories',
                                        'test', 'Accu Chek Instant Test Strip - 2724719440879',
                                        'Accu Chek Instant Test Strip - 2724719440879', 'Accu-Chek', 'Accu-Chek', '',
                                        '',
                                        'https://images-na.ssl-images-amazon.com/images/I/4165nUHCKAL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B07N5ZQWQ6/?language=en_AE',
                                        'https://www.amazon.eg/dp/B07N5ZQWQ6/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'productBox-N26593591A', 'www.noon.com', 'A25bd5bc2', 'eg',
             '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 17.5, "currency": "EGP"}}}',
             '',
             '', '', '', 'test', 'Tactics For Toeic Listening And Reading Test : Practice Test 2 Paperback',
             'Tactics For Toeic Listening And Reading Test : Practice Test 2 Paperback', 'None', '', '', '',
             'https://z.nooncdn.com/products/tr:n-t_400/v1560339743/N26593591A_1.jpg',
             'https://www.noon.com/egypt-en/N26593591A/p', 'https://www.noon.com/egypt-ar/N26593591A/p', '', 0, 0, 0,
             '22-05-25'), ('B091J5RPYR', 'www.amazon.eg', 'A5d566d62', 'eg',
                           '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 101.0, "currency": "EGP"}}}',
                           'Multi Testers', 'Multi Testers', 'Multi Testers', 'Multi Testers', 'test',
                           'automotive voltage test 6-12-24 volt', 'automotive voltage test 6-12-24 volt', 'Besita',
                           'Besita', '', '',
                           'https://images-na.ssl-images-amazon.com/images/I/71Cz2gnqURL._AC_SL1500_.jpg',
                           'https://www.amazon.eg/dp/B091J5RPYR/?language=en_AE',
                           'https://www.amazon.eg/dp/B091J5RPYR/?language=en_AE', '', 0, 0, 0, '22-05-25'), (
             'productBox-Z15E86E90078921222170Z', 'www.noon.com', 'A0fa8dc42', 'eg',
             '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 300.0, "currency": "EGP"}}}',
             '', '', '', '', 'test', '50-Piece Optium Neo Blood Glucometer Test Strips',
             'شرائط Free style optium لقياس نسبة السكر في الدم 50 شريط', 'Freestyle Optium', '', '', '',
             'https://z.nooncdn.com/products/tr:n-t_400/pzsku/Z15E86E90078921222170Z/45/_/1649857272/b67c88c9-dca1-450f-a8eb-0cc8f93d7085.jpg',
             'https://www.noon.com/egypt-en/Z15E86E90078921222170Z/p',
             'https://www.noon.com/egypt-ar/Z15E86E90078921222170Z/p', '', 0, 0, 0, '22-05-25'), (
             'AC098HB0N1XK0NAFAMZ', 'www.jumia.com.eg', 'A2949cb93', 'eg',
             '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 688.0, "currency": "EGP"}}}',
             'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
             'ACCU CHEK Performa - 50 Test Strips - 2 Packs', 'ACCU CHEK Performa - 50 Test Strips - 2 Packs',
             'ACCU CHEK',
             'ACCU CHEK', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/38/721312/1.jpg?2967',
             'https://www.jumia.com.eg/performa-50-test-strips-2-packs-accu-chek-mpg175932.html',
             'https://www.jumia.com.eg/ar/performa-50-test-strips-2-packs-accu-chek-mpg175932.html', '', 0, 0, 0,
             '22-05-25'), ('B09813NBCL', 'www.amazon.eg', 'A3cf38ac6', 'eg',
                           '{"EGP": {"25-05-2022_22:39:03": {"date_time": "25-05-2022 22:39:03", "price": 20.0, "currency": "EGP"}}}',
                           '', '', '', '', 'test', 'Baby check Pregnancy Test', 'Baby check Pregnancy Test',
                           'Baby check',
                           'Baby check', '', '',
                           'https://images-na.ssl-images-amazon.com/images/I/61HI4mvXSOL._AC_SL1500_.jpg',
                           'https://www.amazon.eg/dp/B09813NBCL/?language=en_AE',
                           'https://www.amazon.eg/dp/B09813NBCL/?language=en_AE', '', 0, 0, 0, '22-05-25'), (
             'productBox-N26592738A', 'www.noon.com', 'A4416ef3c', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 749.25, "currency": "EGP"}}}',
             '', '', '', '', 'test',
             'Social Engineering Penetration Testing: Executing Social Engineering Pen Tests, Assessments And Defense Paperback',
             'Social Engineering Penetration Testing: Executing Social Engineering Pen Tests, Assessments And Defense Paperback',
             'None', '', '', '', 'https://z.nooncdn.com/products/tr:n-t_400/v1560339403/N26592738A_1.jpg',
             'https://www.noon.com/egypt-en/N26592738A/p', 'https://www.noon.com/egypt-ar/N26592738A/p', '', 0, 0, 0,
             '22-05-25'), ('productBox-N35523160A', 'www.noon.com', 'A5edf0a2f', 'eg',
                           '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 1262.0, "currency": "EGP"}}}',
                           '', '', '', '', 'test',
                           'PTE Academic: Pearson Test Of English Academic Pearson Test Of English Academic',
                           'PTE Academic: Pearson Test Of English Academic Pearson Test Of English Academic', 'None',
                           '',
                           '', '', 'https://z.nooncdn.com/products/tr:n-t_400/v1584624310/N35523160A_1.jpg',
                           'https://www.noon.com/egypt-en/N35523160A/p', 'https://www.noon.com/egypt-ar/N35523160A/p',
                           '',
                           0, 0, 0, '22-05-25'), ('productBox-N51357436A', 'www.noon.com', 'Aa8e810da', 'eg',
                                                  '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 345.0, "currency": "EGP"}}}',
                                                  '', '', '', '', 'test', 'Ts 50 Test Strip', 'شريحة اختبار TS 50',
                                                  'Contour', '', '', '',
                                                  'https://z.nooncdn.com/products/tr:n-t_400/v1634202681/N51357436A_1.jpg',
                                                  'https://www.noon.com/egypt-en/N51357436A/p',
                                                  'https://www.noon.com/egypt-ar/N51357436A/p', '', 0, 0, 0,
                                                  '22-05-25'), (
             'productBox-N26829827A', 'www.noon.com', 'A70d9bce9', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 127.5, "currency": "EGP"}}}',
             '', '', '', '', 'test', 'Barrons SAT Subject Test U.S.History:The Leader In Test Preparation Paperback',
             'Barrons SAT Subject Test U.S.History:The Leader In Test Preparation Paperback', 'None', '', '', '',
             'https://z.nooncdn.com/products/tr:n-t_400/v1560690197/N26829827A_1.jpg',
             'https://www.noon.com/egypt-en/N26829827A/p', 'https://www.noon.com/egypt-ar/N26829827A/p', '', 0, 0, 0,
             '22-05-25'), ('productBox-N28528024A', 'www.noon.com', 'A4ed260ca', 'eg',
                           '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 327.6, "currency": "EGP"}}}',
                           '', '', '', '', 'test', '(50-Piece) Freestyle Optiumblood Sugar Test Strips',
                           'شرائط اختبار السكر فري ستايل أوبتي بامبلود من (50 قطعة)', 'Abbott', '', '', '',
                           'https://z.nooncdn.com/products/tr:n-t_400/v1599392573/N28528024A_1.jpg',
                           'https://www.noon.com/egypt-en/N28528024A/p', 'https://www.noon.com/egypt-ar/N28528024A/p',
                           '',
                           0, 0, 0, '22-05-25'), ('B091J6G8HL', 'www.amazon.eg', 'A7ce9bd80', 'eg',
                                                  '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 16.0, "currency": "EGP"}}}',
                                                  'Hand Tools', 'Hand Tools', 'Hand Tools', 'Hand Tools', 'test',
                                                  'Ingco HSDT1408 3 In 1 Test Pencil (140mm, Small)',
                                                  'Ingco HSDT1408 3 In 1 Test Pencil (140mm, Small)', 'Ingco', 'Ingco',
                                                  '',
                                                  '',
                                                  'https://images-na.ssl-images-amazon.com/images/I/61Ho1vzkG7L._AC_SL1500_.jpg',
                                                  'https://www.amazon.eg/dp/B091J6G8HL/?language=en_AE',
                                                  'https://www.amazon.eg/dp/B091J6G8HL/?language=en_AE', '', 0, 0, 0,
                                                  '22-05-25'), ('B07P6NGC7H', 'www.amazon.eg', 'A51fe4e61', 'eg',
                                                                '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 290.0, "currency": "EGP"}}}',
                                                                '', '', '', '', 'test',
                                                                'Accu-Chek Performa Test Strips, 50 Strips',
                                                                'Accu-Chek Performa Test Strips, 50 Strips',
                                                                'Accu-Chek',
                                                                'Accu-Chek', '', '',
                                                                'https://images-na.ssl-images-amazon.com/images/I/61r2MaGITmL._AC_SL1500_.jpg',
                                                                'https://www.amazon.eg/dp/B07P6NGC7H/?language=en_AE',
                                                                'https://www.amazon.eg/dp/B07P6NGC7H/?language=en_AE',
                                                                '',
                                                                0, 0, 0, '22-05-25'), (
             'B091J7T9X8', 'www.amazon.eg', 'A55b98a25', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 29.0, "currency": "EGP"}}}',
             'Screwdrivers & Nut Drivers @ Screwdrivers', 'Screwdrivers & Nut Drivers @ Screwdrivers', 'Screwdrivers',
             'Screwdrivers', 'test', 'Ingco Test Screwdriver Tool', 'Ingco Test Screwdriver Tool', 'Ingco', 'Ingco', '',
             '',
             'https://images-na.ssl-images-amazon.com/images/I/41EAuLTimDS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B091J7T9X8/?language=en_AE',
             'https://www.amazon.eg/dp/B091J7T9X8/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09KS4H26F', 'www.amazon.eg', 'A1ab3f7fa', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 450.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test',
                                        'CONTOUR PLUS One Meter with 50 Test Strips',
                                        'CONTOUR PLUS One Meter with 50 Test Strips', 'CONTOUR PLUS', 'CONTOUR PLUS',
                                        '',
                                        '', 'https://m.media-amazon.com/images/I/51+u5zZ5NPL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09KS4H26F/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09KS4H26F/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B0922YZF41', 'www.amazon.eg', 'Aab87db4c', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 44.0, "currency": "EGP"}}}',
             'Voltage Testers @ Hand Tools', '', 'Hand Tools', '', 'test', 'Total Digital Test Pencil (133 mm, 5570)',
             '',
             'Total', 'Total', '', '', 'https://images-na.ssl-images-amazon.com/images/I/514eDPuOmAS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B0922YZF41/?language=en_AE',
             'https://www.amazon.eg/dp/B0922YZF41/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B0922XM4QX', 'www.amazon.eg', 'A72474d01', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 50.0, "currency": "EGP"}}}',
                                        'Clamps @ Spring Clamps', 'Clamps @ Spring Clamps', 'Spring Clamps',
                                        'Spring Clamps', 'test',
                                        'Jumper Wire Double Ended Test Leads Alligator Crocodile Roach Clip',
                                        'Jumper Wire Double Ended Test Leads Alligator Crocodile Roach Clip',
                                        'Jumper Wire',
                                        'Jumper Wire', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/61VgTRkbl4L._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B0922XM4QX/?language=en_AE',
                                        'https://www.amazon.eg/dp/B0922XM4QX/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'GL036ST014SPENAFAMZ', 'www.jumia.com.eg', 'Ac0098fdb', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 190.0, "currency": "EGP"}}}',
             'Test Strips @ Blood Test Strips', 'شرائط الاختبار @ شرائط اختبار الدم', 'Blood Test Strips',
             'شرائط اختبار الدم', 'test', 'GlucoStar Tt Strips 50 Pcs',
             'GlucoStar شرائط جهاز السكر جلوكوستار تي تي 50 شريط', 'GlucoStar', 'GlucoStar', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/01/903442/1.jpg?5967',
             'https://www.jumia.com.eg/glucostar-tt-strips-50-pcs-24430910.html',
             'https://www.jumia.com.eg/ar/glucostar-tt-strips-50-pcs-24430910.html', '', 0, 0, 0, '22-05-25'), (
             'B00FEFBXFC', 'www.amazon.eg', 'A50798649', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 194.0, "currency": "EGP"}}}',
             '', '', '', '', 'test', 'Bestway Pool and Spa Test Strips (58142 - T)',
             'Bestway Pool and Spa Test Strips (58142 - T)', 'Bestway', 'Bestway', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/71xi5DvNQqL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B00FEFBXFC/?language=en_AE',
             'https://www.amazon.eg/dp/B00FEFBXFC/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09X62RFHT', 'www.amazon.eg', 'A95dec938', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 185.0, "currency": "EGP"}}}',
                                        'Pool Maintenance Kits', 'Pool Maintenance Kits', 'Pool Maintenance Kits',
                                        'Pool Maintenance Kits', 'test', 'test kit', 'test kit', 'Generic', 'Generic',
                                        '',
                                        '',
                                        'https://images-na.ssl-images-amazon.com/images/I/61n1tOT41JL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09X62RFHT/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09X62RFHT/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B091BP9C23', 'www.amazon.eg', 'A6a789e0b', 'eg',
             '{"EGP": {"25-05-2022_22:39:04": {"date_time": "25-05-2022 22:39:04", "price": 349.0, "currency": "EGP"}}}',
             'Measuring & Layout', 'Measuring & Layout', 'Measuring & Layout', 'Measuring & Layout', 'test',
             'Chlorine Test for Water', 'Chlorine Test for Water', 'Other', 'Other', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41gJDGekPbL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B091BP9C23/?language=en_AE',
             'https://www.amazon.eg/dp/B091BP9C23/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('GR367ST006NSANAFAMZ', 'www.jumia.com.eg', 'A1e657c8e', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 164.99, "currency": "EGP"}}}',
                                        'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
                                        'Granzia Blood Glucose Perfecta Bianca Strips  - 50 Test Strips',
                                        'Granzia شرائط اختبار السكر في الدم بيرفكتا بيانكا', 'Granzia', 'Granzia', '',
                                        '',
                                        'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/00/310762/1.jpg?0789',
                                        'https://www.jumia.com.eg/granzia-blood-glucose-perfecta-bianca-strips-50-test-strips-26701300.html',
                                        'https://www.jumia.com.eg/ar/granzia-blood-glucose-perfecta-bianca-strips-50-test-strips-26701300.html',
                                        '', 0, 0, 0, '22-05-25'), (
             'VI172HB081VA2NAFAMZ', 'www.jumia.com.eg', 'A4d793f04', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 199.0, "currency": "EGP"}}}',
             'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
             'VIVACHEK INO Blood Glucose Test Strips - 50 Pcs', 'VIVACHEK INO شرايط قياس السكر ٥٠ شريط', 'VIVACHEK INO',
             'VIVACHEK INO', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/13/524122/1.jpg?6046',
             'https://www.jumia.com.eg/vivachek-ino-blood-glucose-test-strips-50-pcs-22142531.html',
             'https://www.jumia.com.eg/ar/vivachek-ino-blood-glucose-test-strips-50-pcs-22142531.html', '', 0, 0, 0,
             '22-05-25'), ('B098YC3BFF', 'www.amazon.eg', 'Ad5193eda', 'eg',
                           '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 35.0, "currency": "EGP"}}}',
                           '', '', '', '', 'test', 'OVULA Pregnancy Test اوفيولا اختبار حمل',
                           'OVULA Pregnancy Test اوفيولا اختبار حمل', 'Generic', 'Generic', '', '',
                           'https://images-na.ssl-images-amazon.com/images/I/71fFgXfDmgL._AC_SL1500_.jpg',
                           'https://www.amazon.eg/dp/B098YC3BFF/?language=en_AE',
                           'https://www.amazon.eg/dp/B098YC3BFF/?language=en_AE', '', 0, 0, 0, '22-05-25'), (
             'BI464ST0VL082NAFAMZ', 'www.jumia.com.eg', 'Ab5802b7f', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 289.0, "currency": "EGP"}}}',
             'Health Tests', 'اختبارات الصحة', 'Health Tests', 'اختبارات الصحة', 'test',
             'BIOZEK Covid 19 Antigen Rapid Test - Nasal Swab - Biozek Netherlands -  2 Tests',
             'BIOZEK اختبار فحص كورونا السريع - كوفيد 19 و اوميكرون-انتيجن - بيوزيك الهولندية -  اختبار 2', 'BIOZEK',
             'BIOZEK', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/53/048162/1.jpg?5827',
             'https://www.jumia.com.eg/biozek-covid-19-antigen-rapid-test-nasal-swab-biozek-netherlands-2-tests-26184035.html',
             'https://www.jumia.com.eg/ar/biozek-covid-19-antigen-rapid-test-nasal-swab-biozek-netherlands-2-tests-26184035.html',
             '', 0, 0, 0, '22-05-25'), ('B0977Y423C', 'www.amazon.eg', 'A20b5bde6', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 118.0, "currency": "EGP"}}}',
                                        '', '', '', '', 'test', 'Oview - Ovulation test with swiss technology',
                                        'Oview - Ovulation test with swiss technology', 'Oview', 'Oview', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/41h8qbm6JVS._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B0977Y423C/?language=en_AE',
                                        'https://www.amazon.eg/dp/B0977Y423C/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B096DD2WZW', 'www.amazon.eg', 'A80996089', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 22.0, "currency": "EGP"}}}',
             'Hand Tools', 'Hand Tools', 'Hand Tools', 'Hand Tools', 'test', 'Ingco Test Pencil - 2724676016209',
             'Ingco Test Pencil - 2724676016209', 'Ingco', 'Ingco', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/31nI7ILAKzS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B096DD2WZW/?language=en_AE',
             'https://www.amazon.eg/dp/B096DD2WZW/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('AC098ST0F31C6NAFAMZ', 'www.jumia.com.eg', 'Ac3652ad2', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 248.85, "currency": "EGP"}}}',
                                        'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
                                        'ACCU CHEK Active Glucose Test Strips - 50 Strips',
                                        'ACCU CHEK شرائط قياس سكر اكوا تشيك (اكتيف) 50 شريط', 'ACCU CHEK', 'ACCU CHEK',
                                        '',
                                        '',
                                        'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/25/335942/1.jpg?2850',
                                        'https://www.jumia.com.eg/accu-chek-active-glucose-test-strips-50-strips-24953352.html',
                                        'https://www.jumia.com.eg/ar/accu-chek-active-glucose-test-strips-50-strips-24953352.html',
                                        '', 0, 0, 0, '22-05-25'), (
             'GE810HB0CZ21WNAFAMZ', 'www.jumia.com.eg', 'A6361cabc', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 114.3, "currency": "EGP"}}}',
             'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
             'On Call Plus Blood Glucose Test Strips  - 50 Strips',
             'On Call Plus Blood Glucose Test Strips  - 50 Strips',
             'Generic', 'Generic', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/21/791012/1.jpg?3143',
             'https://www.jumia.com.eg/on-call-plus-blood-glucose-test-strips-50-strips-generic-mpg180173.html',
             'https://www.jumia.com.eg/ar/on-call-plus-blood-glucose-test-strips-50-strips-generic-mpg180173.html', '',
             0,
             0, 0, '22-05-25'), ('GL370ST14KCPANAFAMZ', 'www.jumia.com.eg', 'Aaf1666f5', 'eg',
                                 '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 189.0, "currency": "EGP"}}}',
                                 'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
                                 'GlucoDr Test Strips - 50 Tests', '', 'GlucoDr', '', '', '',
                                 'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/68/134222/1.jpg?1567',
                                 'https://www.jumia.com.eg/glucodr-test-strips-50-tests-medcare-mpg774050.html',
                                 'https://www.jumia.com.eg/ar/glucodr-test-strips-50-tests-medcare-mpg774050.html', '',
                                 0,
                                 0, 0, '22-05-25'), ('RU372ST0370ZMNAFAMZ', 'www.jumia.com.eg', 'A29b55f2f', 'eg',
                                                     '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 195.0, "currency": "EGP"}}}',
                                                     'Test Strips @ Blood Test Strips',
                                                     'شرائط الاختبار @ شرائط اختبار الدم', 'Blood Test Strips',
                                                     'شرائط اختبار الدم', 'test',
                                                     'Ruby Medi Smart Ruby Blood Glucose Test Strips "50 Strips"', '',
                                                     'Ruby', '', '', '',
                                                     'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/05/366722/1.jpg?8604',
                                                     'https://www.jumia.com.eg/ruby-medi-smart-ruby-blood-glucose-test-strips-50-strips-22766350.html',
                                                     'https://www.jumia.com.eg/ar/ruby-medi-smart-ruby-blood-glucose-test-strips-50-strips-22766350.html',
                                                     '', 0, 0, 0, '22-05-25'), (
             'B07P6NKTYJ', 'www.amazon.eg', 'A00c86030', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 220.0, "currency": "EGP"}}}',
             'Monitors @ Diabetic Monitors & Accessories', 'Monitors @ Diabetic Monitors & Accessories',
             'Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories', 'test',
             'Contour TS Glucose Blood Glucose Test Strips, 50 Strips',
             'Contour TS Glucose Blood Glucose Test Strips, 50 Strips', 'Contour TS', 'Contour TS', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/517kqSPykxL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B07P6NKTYJ/?language=en_AE',
             'https://www.amazon.eg/dp/B07P6NKTYJ/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B093QDNLYQ', 'www.amazon.eg', 'Ab8227c77', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 138.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test', 'Fine Test blood Glucose Monitor',
                                        'Fine Test blood Glucose Monitor', 'Fine test', 'Fine test', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/61UkY5AePVS._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B093QDNLYQ/?language=en_AE',
                                        'https://www.amazon.eg/dp/B093QDNLYQ/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'BA396ST0AW00ANAFAMZ', 'www.jumia.com.eg', 'A9f5d474c', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 20.0, "currency": "EGP"}}}',
             'Family Planning Tests @ Pregnancy Tests', '', 'Pregnancy Tests', '', 'test',
             'Baby Check One Time Pregnancy Test', '', 'Baby', '', '', '',
             'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/18/289162/1.jpg?3309',
             'https://www.jumia.com.eg/check-one-time-pregnancy-test-baby-mpg872830.html',
             'https://www.jumia.com.eg/ar/check-one-time-pregnancy-test-baby-mpg872830.html', '', 0, 0, 0, '22-05-25'),
         (
             'B0998CFX7B', 'www.amazon.eg', 'A89a83e10', 'eg',
             '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 225.0, "currency": "EGP"}}}',
             'Monitors @ Diabetic Monitors & Accessories', 'Monitors @ Diabetic Monitors & Accessories',
             'Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories', 'test',
             'Bayer Contour Plus Glucose Test Strips (50 Pieces)', 'Bayer Contour Plus Glucose Test Strips (50 Pieces)',
             'Bayer', 'Bayer', '', '', 'https://images-na.ssl-images-amazon.com/images/I/416eXdWbYCL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B0998CFX7B/?language=en_AE',
             'https://www.amazon.eg/dp/B0998CFX7B/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B0968WY2N4', 'www.amazon.eg', 'A78fada4e', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:05": {"date_time": "25-05-2022 22:39:05", "price": 699.0, "currency": "EGP"}}}',
                                        '', '', '', '', 'test',
                                        'Amazing Roulette Shocking Roulette Lie Detector Electric Polygraph Test Finger Toy Party Drinking Game Without Battery',
                                        'Amazing Roulette Shocking Roulette Lie Detector Electric Polygraph Test Finger Toy Party Drinking Game Without Battery',
                                        'Amazing Roulette', 'Amazing Roulette', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/51UZBEPrRsL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B0968WY2N4/?language=en_AE',
                                        'https://www.amazon.eg/dp/B0968WY2N4/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B092334GC4', 'www.amazon.eg', 'A3ab80479', 'eg',
             '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 14.0, "currency": "EGP"}}}',
             'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'Circuit Testers', 'test',
             'TOTAL TOOLS Test pencil - THT291408', 'TOTAL TOOLS Test pencil - THT291408', 'Total', 'Total', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/51QKaYmq72S._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B092334GC4/?language=en_AE',
             'https://www.amazon.eg/dp/B092334GC4/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B09SPN6DSM', 'www.amazon.eg', 'Af9b36248', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 210.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test',
                                        'SandaCare Adura Blood Glucose Test Strips',
                                        'SandaCare Adura Blood Glucose Test Strips', 'Sandacare', 'Sandacare', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/71iOOtVDfvL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B09SPN6DSM/?language=en_AE',
                                        'https://www.amazon.eg/dp/B09SPN6DSM/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B081JMGFQQ', 'www.amazon.eg', 'Acb9d5a16', 'eg',
             '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 959.0, "currency": "EGP"}}}',
             '', '', '', '', 'test',
             'Qiilu Cylinder Leak Detector - Engine Pressure Gauge Compression r Kit for Piston Ring, Valve, Head Gasket Diagnosis Leakage Test Set',
             'Qiilu Cylinder Leak Detector - Engine Pressure Gauge Compression r Kit for Piston Ring, Valve, Head Gasket Diagnosis Leakage Test Set',
             'Qiilu', 'Qiilu', '', '', 'https://images-na.ssl-images-amazon.com/images/I/51ZfAjJ2LDL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B081JMGFQQ/?language=en_AE',
             'https://www.amazon.eg/dp/B081JMGFQQ/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('IN480ST19070UNAFAMZ', 'www.jumia.com.eg', 'A0726d1db', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 174.5, "currency": "EGP"}}}',
                                        'Test Strips', 'شرائط الاختبار', 'Test Strips', 'شرائط الاختبار', 'test',
                                        'Infopia Fine Test 50 Strips',
                                        'Infopia Infopia شرائط قياس سكر في الدم فاين تست 50 شريط', 'Infopia', 'Infopia',
                                        '',
                                        '',
                                        'https://eg.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/75/591822/1.jpg?2371',
                                        'https://www.jumia.com.eg/fine-test-50-strips-infopia-mpg878180.html',
                                        'https://www.jumia.com.eg/ar/fine-test-50-strips-infopia-mpg878180.html', '', 0,
                                        0,
                                        0, '22-05-25'), ('B09V19YSKW', 'www.amazon.eg', 'Ab7c1d8dc', 'eg',
                                                         '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 44.0, "currency": "EGP"}}}',
                                                         'Automotive Diagnostic, Test & Measuring Tools',
                                                         'Automotive Diagnostic, Test & Measuring Tools',
                                                         'Automotive Diagnostic, Test & Measuring Tools',
                                                         'Automotive Diagnostic, Test & Measuring Tools', 'test',
                                                         'TOTAL TOOLS Digital Test Pencil -THT292201',
                                                         'TOTAL TOOLS Digital Test Pencil -THT292201', 'Generic',
                                                         'Generic',
                                                         '', '',
                                                         'https://images-na.ssl-images-amazon.com/images/I/71nDXa3m11L._AC_SL1500_.jpg',
                                                         'https://www.amazon.eg/dp/B09V19YSKW/?language=en_AE',
                                                         'https://www.amazon.eg/dp/B09V19YSKW/?language=en_AE', '', 0,
                                                         0, 0,
                                                         '22-05-25'), ('B091CX93XV', 'www.amazon.eg', 'A021272bb', 'eg',
                                                                       '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 34.0, "currency": "EGP"}}}',
                                                                       '', '', '', '', 'test',
                                                                       'DOUBLE-END ALLIGATOR CLIP WIRE TEST CABLE DOUBLE-END ALLIGATOR CLIP WIRE TEST CABLE CROCODILE (30CM / 5-PIECE PACK)(30CM / 10-PIECE PACK)',
                                                                       'DOUBLE-END ALLIGATOR CLIP WIRE TEST CABLE DOUBLE-END ALLIGATOR CLIP WIRE TEST CABLE CROCODILE (30CM / 5-PIECE PACK)(30CM / 10-PIECE PACK)',
                                                                       'Other', 'Other', '', '',
                                                                       'https://images-na.ssl-images-amazon.com/images/I/51NoSAyU7mL._AC_SL1500_.jpg',
                                                                       'https://www.amazon.eg/dp/B091CX93XV/?language=en_AE',
                                                                       'https://www.amazon.eg/dp/B091CX93XV/?language=en_AE',
                                                                       '', 0, 0, 0, '22-05-25'), (
             'B09X2C3LC2', 'www.amazon.eg', 'A3b5f747b', 'eg',
             '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 230.0, "currency": "EGP"}}}',
             '', '', '', '', 'test', 'Mo-Screen Covid-19 Rapid Antigen Test Home Corona Fast Test',
             'Mo-Screen Covid-19 Rapid Antigen Test Home Corona Fast Test', 'MoLab', 'MoLab', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/21h9bJr4pPL._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B09X2C3LC2/?language=en_AE',
             'https://www.amazon.eg/dp/B09X2C3LC2/?language=en_AE',
             '', 0, 0, 0, '22-05-25'), ('B08X5YZ2SF', 'www.amazon.eg', 'Ae6bb9f5a', 'eg',
                                        '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 260.0, "currency": "EGP"}}}',
                                        'Monitors @ Diabetic Monitors & Accessories',
                                        'Monitors @ Diabetic Monitors & Accessories', 'Diabetic Monitors & Accessories',
                                        'Diabetic Monitors & Accessories', 'test', 'Bionime GS100 Test Strips',
                                        'Bionime GS100 Test Strips', 'Bionime', 'Bionime', '', '',
                                        'https://images-na.ssl-images-amazon.com/images/I/31hTK7H2-QL._AC_SL1500_.jpg',
                                        'https://www.amazon.eg/dp/B08X5YZ2SF/?language=en_AE',
                                        'https://www.amazon.eg/dp/B08X5YZ2SF/?language=en_AE', '', 0, 0, 0, '22-05-25'),
         (
             'B094492FQS', 'www.amazon.eg', 'A3cc24e5e', 'eg',
             '{"EGP": {"25-05-2022_22:39:06": {"date_time": "25-05-2022 22:39:06", "price": 265.0, "currency": "EGP"}}}',
             'Monitors @ Blood Pressure Monitors & Accessories', 'Monitors @ Blood Pressure Monitors & Accessories',
             'Blood Pressure Monitors & Accessories', 'Blood Pressure Monitors & Accessories', 'test',
             'Bionime Rightest Wiz Blood Glucose Test Strips, 50 Strips',
             'Bionime Rightest Wiz Blood Glucose Test Strips, 50 Strips', 'Bionime', 'Bionime', '', '',
             'https://images-na.ssl-images-amazon.com/images/I/41XEM3PWzwS._AC_SL1500_.jpg',
             'https://www.amazon.eg/dp/B094492FQS/?language=en_AE',
             'https://www.amazon.eg/dp/B094492FQS/?language=en_AE',
             '', 0, 0, 0, '22-05-25')]

#
# for i in items:
#     print(i)
import requests
import mysql.connector
from mysql.connector import errorcode

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0',
}

r = requests.post('http://api-v1.onlinewebshop.net/', data={'data': items}
                  )
print(r.content)


def db_connection():
    try:
        conn = mysql.connector.connect(user="mmk4m1fm109k",
                                       password="pscale_pw_YHKalJ1HnIt2TKbSsKWNEAwpuMtV_WxBBlf2_qlHCKk",
                                       host="rpdfka86np0m.eu-central-2.psdb.cloud", port=3306, database="main_schema")

    except mysql.connector.Error as err:
        if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
            print("Something is wrong with the user name or password")
        elif err.errno == errorcode.ER_BAD_DB_ERROR:
            print("Database does not exist")
        else:
            print(f"ERROR {err}")
    else:
        return conn


# db_connection()

# connection = db_connection()
# cursor = connection.cursor()
# insert_query = f"""INSERT INTO products_eg (source_identifier_code, website_name, UIC, country, price_data,
#                        product_category_en, product_category_ar, product_type_en, product_type_ar,
#                        search_key, title_en, title_ar, brand_en, brand_ar, item_specs_en,
#                        item_specs_ar, images_url, product_direct_link_en, product_direct_link_ar, item_upc,
#                        sold_out, rating, number_of_reviews, item_date) VALUES
#                        (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
#                        %s, %s, %s);"""
# cursor.executemany(insert_query, items)
# connection.commit()
# connection.close()

def db_infos():
    db_host_1 = {
        'user': 'admin',
        'password': 'PTS-0000',
        'host': '130.162.40.58',
        'database': 'main_schema'
    }

    db_host_2 = {
        'user': 'mmk4m1fm109k',
        'password': 'pscale_pw_YHKalJ1HnIt2TKbSsKWNEAwpuMtV_WxBBlf2_qlHCKk',
        'host': 'rpdfka86np0m.eu-central-2.psdb.cloud',
        'database': 'main_schema'
    }
    return db_host_1, db_host_2

print(db_infos()[1])