import mysql.connector
from mysql.connector import errorcode
import json
import uuid
from hashlib import blake2b

data = {'AM423MW0XCWKUNAFAMZ': {'item_title': 'American Eagle Polo Shirt - Somber Navy',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0XCWKUNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-polo-shirt-somber-navy-22492065.html',
                                'item_price': '240.00', 'item_uid': 'AM423MW0XCWKUNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:46', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'American Eagle تي-شيرت بولو'},
        'ME773MW16DX40NAFAMZ': {'item_title': 'Mesery Bundle Of Three Cotton Stretch Plain Tank Tops',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/ME773MW16DX40NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/mesery-bundle-of-three-cotton-stretch-plain-tank-tops-21339117.html',
                                'item_price': '99.00', 'item_uid': 'ME773MW16DX40NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Mesery 3 توب حماله عريضه قطن استريتش'},
        'B0992XC4BX': {
            'item_title': '\n\n\n\n\n\n\n\nandora Cotton Regular Fit Button Down Collar Gingham Shirt for Men\n\n\n\n\n\n\n, Select',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B0992XC4BX.jpg',
            'item_url': 'https://www.amazon.eg/dp/B08WJN9L1H/?language=en_AE', 'item_price': 'EGP 159.00',
            'item_uid': 'B0992XC4BX', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
            'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': {'3XL': 'found'},
            'item_title_ar': '\n\n\n\n\n\n\n\nandora Cotton Regular Fit Button Down Collar Gingham Shirt for Men\n\n\n\n\n\n\n'},
        'AM423MW0A755ANAFAMZ': {'item_title': 'American Eagle Super Soft Graphic T-Shirt - Olive',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0A755ANAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-graphic-t-shirt-olive-22492171.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW0A755ANAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle تي-شورت سوبر سوفت مزين بطبعة'},
        'ME773FA0UGXD0NAFAMZ': {'item_title': 'Mesery Bundle Of Six Spaghetti Sleeves Plain Tank Tops.',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/ME773FA0UGXD0NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/mesery-bundle-of-six-spaghetti-sleeves-plain-tank-tops.-21287115.html',
                                'item_price': '149.00', 'item_uid': 'ME773FA0UGXD0NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:48', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Mesery 6 حماله رفيعه قطن'},
        'HO993MW158EHBNAFAMZ': {'item_title': "Ho Holland Men's Polo Shirt - White",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/HO993MW158EHBNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/ho-holland-mens-polo-shirt-white-17265296.html',
                                'item_price': '189.00', 'item_uid': 'HO993MW158EHBNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:49', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Ho Holland بولو تيشرت من ماركة هو-هولاند - ابيض'},
        'AM423MW17RZNYNAFAMZ': {'item_title': 'American Eagle Super Soft Graphic T-Shirt - Camper Green',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW17RZNYNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-graphic-t-shirt-camper-green-22492537.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW17RZNYNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:47', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle تي-شورت سوبر سوفت مزين بطبعة'},
        'ME773MW0K6TACNAFAMZ': {'item_title': 'Mesery Bundle Of Three Cotton Stretch Plain Spaghetti Tops',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/ME773MW0K6TACNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/mesery-bundle-of-three-cotton-stretch-plain-spaghetti-tops-21201933.html',
                                'item_price': '89.00', 'item_uid': 'ME773MW0K6TACNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:49', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Mesery 3 توب حماله رفيعه قطن استريتش'},
        'B08WJN262Y': {'item_title': '\n\n\n\n\n\n\n\nFaconnable Shirt For Men\n\n\n\n\n\n\n',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B08WJN262Y.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B08WJN262Y/?language=en_AE', 'item_price': 'EGP 2,025.00',
                       'item_uid': 'B08WJN262Y', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:47',
                       'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
                       'item_title_ar': '\n\n\n\n\n\n\n\nFaconnable Shirt For Men\n\n\n\n\n\n\n'}, 'B091C74331': {
        'item_title': '\n\n\n\n\n\n\n\nAdjustable Men Shirt Stays Garters Suspenders Shirt Holder\n\n\n\n\n\n\n',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B091C74331.jpg',
        'item_url': 'https://www.amazon.eg/dp/B091C74331/?language=en_AE', 'item_price': 'EGP 82.00',
        'item_uid': 'B091C74331', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
        'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
        'item_title_ar': '\n\n\n\n\n\n\n\nAdjustable Men Shirt Stays Garters Suspenders Shirt Holder\n\n\n\n\n\n\n'},
        'B0994NPN8K': {'item_title': '\n\n\n\n\n\n\n\nSPORT ROUND T SHIRT\n\n\n\n\n\n\n',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B0994NPN8K.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B0994NPN8K/?language=en_AE', 'item_price': 'EGP 79.00',
                       'item_uid': 'B0994NPN8K', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
                       'item_title_ar': '\n\n\n\n\n\n\n\nSPORT ROUND T SHIRT\n\n\n\n\n\n\n'},
        'AM423MW10USZ8NAFAMZ': {'item_title': 'American Eagle Polo Shirt - Blue Mist',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW10USZ8NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-polo-shirt-blue-mist-21430916.html',
                                'item_price': '240.00', 'item_uid': 'AM423MW10USZ8NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'American Eagle Polo Shirt - Blue Mist'},
        'IZ873MW0HCH87NAFAMZ': {'item_title': 'Izor Bi-tone Half Sleeves Rounded Tee - Burgindy & Navy Blue',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/IZ873MW0HCH87NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/izor-bi-tone-half-sleeves-rounded-tee-burgindy-navy-blue-17653192.html',
                                'item_price': '105.00', 'item_uid': 'IZ873MW0HCH87NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:49', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Izor Bi-tone Half Sleeves Rounded Tee - Burgindy & Navy Blue'},
        'B096CSJK3D': {
            'item_title': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Buttoned Polo T-Shirt\n\n\n\n\n\n\n',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B096CSJK3D.jpg',
            'item_url': 'https://www.amazon.eg/dp/B096CSJK3D/?language=en_AE', 'item_price': 'EGP 89.00',
            'item_uid': 'B096CSJK3D', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:48',
            'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
            'item_title_ar': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Buttoned Polo T-Shirt\n\n\n\n\n\n\n'},
        'B0966V9VVK': {'item_title': '\n\n\n\n\n\n\n\nDolab Short Sleeves Round Neck Basic T-Shirt\n\n\n\n\n\n\n',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B0966V9VVK.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B0966V9VVK/?language=en_AE', 'item_price': 'EGP 59.00',
                       'item_uid': 'B0966V9VVK', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:48',
                       'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
                       'item_title_ar': '\n\n\n\n\n\n\n\nDolab Short Sleeves Round Neck Basic T-Shirt\n\n\n\n\n\n\n'},
        'B092F1W9RS': {
            'item_title': '\n\n\n\n\n\n\n\nLumex Printed Elastic Cuffs Jumpsuit with Short Sleeves T-Shirt For Kids - Green, 3-6 Months\n\n\n\n\n\n\n',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B092F1W9RS.jpg',
            'item_url': 'https://www.amazon.eg/dp/B092F1W9RS/?language=en_AE', 'item_price': 'EGP 100.00',
            'item_uid': 'B092F1W9RS', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
            'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
            'item_title_ar': '\n\n\n\n\n\n\n\nLumex Printed Elastic Cuffs Jumpsuit with Short Sleeves T-Shirt For Kids - Green, 3-6 Months\n\n\n\n\n\n\n'},
        'B099CGJJN7': {
            'item_title': '\n\n\n\n\n\n\n\nMagma Printed Round Neck Short Sleeves Regular-Fit Sports T-Shirt for Men\n\n\n\n\n\n\n, Select',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B099CGJJN7.jpg',
            'item_url': 'https://www.amazon.eg/dp/B08WJLD64C/?language=en_AE', 'item_price': 'EGP 124.00 - EGP 209.00',
            'item_uid': 'B099CGJJN7', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
            'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': {'Medium': 'found', 'X-Large': 'found'},
            'item_title_ar': '\n\n\n\n\n\n\n\nMagma Printed Round Neck Short Sleeves Regular-Fit Sports T-Shirt for Men\n\n\n\n\n\n\n'},
        'SU352FA0GJEPHNAFAMZ': {'item_title': 'Sun Set Buttoned Down Blouse For Women - Beige',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/SU352FA0GJEPHNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/sun-set-buttoned-down-blouse-for-women-beige-18397772.html',
                                'item_price': '167.00', 'item_uid': 'SU352FA0GJEPHNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:49', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Sun Set شميز للنساء من صن سيت - سوفت - بيج'}, 'B0996NL68V': {
        'item_title': '\n\n\n\n\n\n\n\nGiggles Round Neck Contrast Print T-Shirt for Boys\n\n\n\n\n\n\n, Select',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B0996NL68V.jpg',
        'item_url': 'https://www.amazon.eg/dp/B08WJN5TJG/?language=en_AE', 'item_price': 'EGP 99.00',
        'item_uid': 'B0996NL68V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
        'item_website': 'www.amazon.eg', 'tree': '',
        'item_sizes': {'9 Years': 'found', '10 Years': 'found', '11 Years': 'found', '12 Years': 'found',
                       '13 Years': 'found', '14 Years': 'found', '15 Years': 'found', '16 Years': 'found'},
        'item_title_ar': '\n\n\n\n\n\n\n\nGiggles Round Neck Contrast Print T-Shirt for Boys\n\n\n\n\n\n\n'},
        'AM423MW1L8DXQNAFAMZ': {'item_title': 'American Eagle Super Soft Graphic T-Shirt - Green',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW1L8DXQNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-graphic-t-shirt-green-22492169.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW1L8DXQNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle تي-شورت سوبر سوفت مزين بطبعة'},
        'AM423MW11QSG0NAFAMZ': {'item_title': 'American Eagle Pique Polo Shirt - NAVY',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW11QSG0NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-pique-polo-shirt-navy-21759336.html',
                                'item_price': '330.00', 'item_uid': 'AM423MW11QSG0NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Pique Polo Shirt - NAVY'},
        'KA433MW062KDGNAFAMZ': {'item_title': 'Kady Short Sleeves Buttoned Ribbed Polo Shirt - Navy Blue',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/KA433MW062KDGNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/kady-short-sleeves-buttoned-ribbed-polo-shirt-navy-blue-21479101.html',
                                'item_price': '79.00', 'item_uid': 'KA433MW062KDGNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Kady Short Sleeves Buttoned Ribbed Polo Shirt - Navy Blue'},
        'AM423MW18O7DONAFAMZ': {'item_title': 'American Eagle Pique Polo Shirt - Black',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW18O7DONAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-pique-polo-shirt-black-21423057.html',
                                'item_price': '330.00', 'item_uid': 'AM423MW18O7DONAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Pique Polo Shirt - Black'},
        'HO993MW1CVY9KNAFAMZ': {'item_title': "Ho Holland Men's Polo Shirt - Dark Blue",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/HO993MW1CVY9KNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/ho-holland-mens-polo-shirt-dark-blue-21321128.html',
                                'item_price': '199.00', 'item_uid': 'HO993MW1CVY9KNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Ho Holland بولو تيشرت من ماركة هو-هولاند - كحلي'}, 'B091JLRFFB': {
        'item_title': '\n\n\n\n\n\n\n\nCottonil Combed Under Shirt - Set of 3 Hlaf Sleeves Under shirts - 100% Cotton - for Men\n\n\n\n\n\n\n, Select',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B091JLRFFB.jpg',
        'item_url': 'https://www.amazon.eg/dp/B09231J96N/?language=en_AE', 'item_price': 'EGP 165.99 - EGP 175.00',
        'item_uid': 'B091JLRFFB', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:53',
        'item_website': 'www.amazon.eg', 'tree': '',
        'item_sizes': {'2X': 'found', 'M': 'found', 'L': 'found', 'XL': 'found'},
        'item_title_ar': '\n\n\n\n\n\n\n\nCottonil Combed Under Shirt - Set of 3 Hlaf Sleeves Under shirts - 100% Cotton - for Men\n\n\n\n\n\n\n'},
        'B098MY2VRY': {
            'item_title': '\n\n\n\n\n\n\n\nAndora Cotton Basic Long Sleeves Shirt for Men\n\n\n\n\n\n\n, Select',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B098MY2VRY.jpg',
            'item_url': 'https://www.amazon.eg/dp/B08WJLB9SH/?language=en_AE', 'item_price': 'EGP 170.00 - EGP 189.00',
            'item_uid': 'B098MY2VRY', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
            'item_website': 'www.amazon.eg', 'tree': '',
            'item_sizes': {'3XL': 'found', 'M': 'found', 'Medium': 'found', 'Large': 'found', 'X-Large': 'found',
                           'XX-Large': 'found', 'XXX-Large': 'found'},
            'item_title_ar': '\n\n\n\n\n\n\n\nAndora Cotton Basic Long Sleeves Shirt for Men\n\n\n\n\n\n\n'},
        'IZ873MW0QDS0TNAFAMZ': {'item_title': 'Izor Mandarin Collar Pique Polo Shirt - Maroon',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/IZ873MW0QDS0TNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/izor-mandarin-collar-pique-polo-shirt-maroon-16821344.html',
                                'item_price': '115.00', 'item_uid': 'IZ873MW0QDS0TNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:54', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Izor Mandarin Collar Pique Polo Shirt - Maroon'}, 'B096D5Y138': {
        'item_title': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Embroidered Polo T-Shirt\n\n\n\n\n\n\n',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B096D5Y138.jpg',
        'item_url': 'https://www.amazon.eg/dp/B096D5Y138/?language=en_AE', 'item_price': 'EGP 99.00',
        'item_uid': 'B096D5Y138', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:53',
        'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
        'item_title_ar': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Embroidered Polo T-Shirt\n\n\n\n\n\n\n'},
        'B099T95KPY': {'item_title': '\nThe ultimate T- shirt collection\n',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B099T95KPY.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B099T95KPY/?language=en_AE', 'item_price': ' EGP 206.00 ',
                       'item_uid': 'B099T95KPY', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
                       'item_title_ar': '\nThe ultimate T- shirt collection\n'}, 'B098PMJKRR': {
        'item_title': '\n\n\n\n\n\n\n\nAndora Front Embroidered Letters Side Slits Short Sleeves Shirt Neck Polo Shirt for Boys\n\n\n\n\n\n\n, Select',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B098PMJKRR.jpg',
        'item_url': 'https://www.amazon.eg/dp/B096L7G1RC/?language=en_AE', 'item_price': 'EGP 149.00',
        'item_uid': 'B098PMJKRR', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:47',
        'item_website': 'www.amazon.eg', 'tree': '',
        'item_sizes': {'6 Years': 'found', '8 Years': 'found', '10 Years': 'found', '12 Years': 'found',
                       '16 Years': 'found'},
        'item_title_ar': '\n\n\n\n\n\n\n\nAndora Front Embroidered Letters Side Slits Short Sleeves Shirt Neck Polo Shirt for Boys\n\n\n\n\n\n\n'},
        'AM423MW02BNW4NAFAMZ': {'item_title': 'American Eagle Polo Shirt - Starlet Pink',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW02BNW4NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-polo-shirt-starlet-pink-21430930.html',
                                'item_price': '240.00', 'item_uid': 'AM423MW02BNW4NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Polo Shirt - Starlet Pink'},
        'N39962987V': {'item_title': 'Ditsy Print Navy Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962987V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962987V/p', 'item_price': '530',
                       'item_uid': 'N39962987V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'طبعة ديتسي أزرق كحلي'},
        'N44817383V': {'item_title': 'plain basic long sleeve shirt with collared neck Orange',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N44817383V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N44817383V/p', 'item_price': '149.00',
                       'item_uid': 'N44817383V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص أساسي سادة بأكمام طويلة ورقبة بياقة برتقالي'},
        'N41205571V': {'item_title': 'Contrast Pattern Shirt Black',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N41205571V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N41205571V/p', 'item_price': '493',
                       'item_uid': 'N41205571V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بنقشة متباينة أسود'},
        'AM423MW0MPB5ONAFAMZ': {'item_title': 'American Eagle Slim Flex Polo Shirt - Burgundy',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0MPB5ONAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-slim-flex-polo-shirt-burgundy-21423183.html',
                                'item_price': '330.00', 'item_uid': 'AM423MW0MPB5ONAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:48', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Slim Flex Polo Shirt - Burgundy'},
        'ME773MW0LYC64NAFAMZ': {'item_title': 'Mesery Bundle Of Three Cotton Stretch Plain Spaghetti Tops',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/ME773MW0LYC64NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/mesery-bundle-of-three-cotton-stretch-plain-spaghetti-tops-21047863.html',
                                'item_price': '89.00', 'item_uid': 'ME773MW0LYC64NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Mesery 3 توب حماله رفيعه قطن استريتش'},
        'IZ873FA12R8P2NAFAMZ': {'item_title': "Izor Men's Half Sleeves T-Shirt - Black",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/IZ873FA12R8P2NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/izor-mens-half-sleeves-t-shirt-black-9369056.html',
                                'item_price': '115.00', 'item_uid': 'IZ873FA12R8P2NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': "Izor Men's Half Sleeves T-Shirt - Black"},
        'AM423MW0FHWFINAFAMZ': {'item_title': 'American Eagle Polo Shirt - Washed Olive',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0FHWFINAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-polo-shirt-washed-olive-22492062.html',
                                'item_price': '240.00', 'item_uid': 'AM423MW0FHWFINAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'American Eagle تي-شيرت بولو'},
        'AC452MW1FY9UHNAFAMZ': {'item_title': 'Activ Simple Basic Round T-shirt - Indigo',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AC452MW1FY9UHNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/simple-basic-round-t-shirt-indigo-activ-mpg783049.html',
                                'item_price': '69.00', 'item_uid': 'AC452MW1FY9UHNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Activ Simple Basic Round T-shirt - Indigo'},
        'AM423MW1JC7U8NAFAMZ': {'item_title': 'American Eagle Ss Core Brand Cvc Hthrs - 180Gsm - Gray',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW1JC7U8NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-ss-core-brand-cvc-hthrs-180gsm-gray-21984929.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW1JC7U8NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Ss Core Brand Cvc Hthrs - 180Gsm - Gray'},
        'N39961330V': {'item_title': 'Dual Pocket Long Sleeve Shirt Navy Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961330V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961330V/p', 'item_price': '492',
                       'item_uid': 'N39961330V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:48',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بأكمام طويلة وجيب مزدوج أزرق كحلي'},
        'N39959976V': {'item_title': 'Checked Chest Pocket Shirt Dark Blue/Light Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39959976V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39959976V/p', 'item_price': '346',
                       'item_uid': 'N39959976V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بنقشة مربعات وجيب على الصدر أزرق داكن/أزرق فاتح'},
        'IZ873FA0GQ7BANAFAMZ': {'item_title': 'Izor Mandarin Collar T-Shirt - Grey',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/IZ873FA0GQ7BANAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/izor-mandarin-collar-t-shirt-grey-9369082.html',
                                'item_price': '115.00', 'item_uid': 'IZ873FA0GQ7BANAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:52', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Izor Mandarin Collar T-Shirt - Grey'},
        'N40617999V': {'item_title': 'Side Pocket Short Sleeve Shirt White Oxford',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40617999V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40617999V/p', 'item_price': '311',
                       'item_uid': 'N40617999V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بأكمام قصيرة وجيوب جانبية أبيض أكسفورد'},
        'N39962223V': {'item_title': 'Bastian 3 Pocket Detail Shirt Dusty Olive Relaxed',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962223V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962223V/p', 'item_price': '401',
                       'item_uid': 'N39962223V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص باستيان بـ3 جيوب زيتوني داستي مقاس فضفاض'},
        'N33126010V': {'item_title': 'Cuban Collar Shirt Black',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126010V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126010V/p', 'item_price': '501',
                       'item_uid': 'N33126010V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بياقة كوبية أسود'},
        'N40618112V': {'item_title': 'Brunswick Slub Polo Oatmeal Texture',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40618112V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40618112V/p', 'item_price': '245',
                       'item_uid': 'N40618112V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بولو برونزويك سلاب نسيج بلون الشوفان'},
        'HO993MW1MJN8ONAFAMZ': {'item_title': "Ho Holland Men's Polo Shirt - Multi Color",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/HO993MW1MJN8ONAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/ho-holland-mens-polo-shirt-multi-color-21343389.html',
                                'item_price': '185.00', 'item_uid': 'HO993MW1MJN8ONAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'Ho Holland بولو تيشرت - بنفسجي و اسود'},
        'AM423MW19C4VKNAFAMZ': {'item_title': 'American Eagle Super Soft Eagle Graphic T-Shirt - White',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW19C4VKNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-eagle-graphic-t-shirt-white-21984167.html',
                                'item_price': '220.00', 'item_uid': 'AM423MW19C4VKNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Super Soft Eagle Graphic T-Shirt - White'},
        'HO993MW0ZBQNCNAFAMZ': {'item_title': "Ho Holland Men's Polo Shirt - Multi Color",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/HO993MW0ZBQNCNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/ho-holland-mens-polo-shirt-multi-color-21343395.html',
                                'item_price': '185.00', 'item_uid': 'HO993MW0ZBQNCNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:48', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Ho Holland بولو تيشرت من ماركة هو-هولاند - رصاصي و اسود'},
        'KA433MW154ZWKNAFAMZ': {'item_title': 'Kady Tri-Tone Pique Polo Shirt - Navy Blue, Wine & White',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/KA433MW154ZWKNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/kady-tri-tone-pique-polo-shirt-navy-blue-wine-white-21479096.html',
                                'item_price': '79.00', 'item_uid': 'KA433MW154ZWKNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Kady Tri-Tone Pique Polo Shirt - Navy Blue, Wine & White'},
        'AM423MW05ZEQ2NAFAMZ': {'item_title': 'American Eagle Active Graphic T- Shirt -  White',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW05ZEQ2NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-active-graphic-t-shirt-white-22105001.html',
                                'item_price': '220.00', 'item_uid': 'AM423MW05ZEQ2NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Active Graphic T-Shirt - White'},
        'BR968MW0GC58QNAFAMZ': {'item_title': "Fashion Men's Big Size Long Sleeve Formal Shirt-Blue",
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/BR968MW0GC58QNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/fashion-mens-big-size-long-sleeve-formal-shirt-blue-22504472.html',
                                'item_price': '299.00', 'item_uid': 'BR968MW0GC58QNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'Fashion قميص رسمي رجالي بأكمام طويلة مقاس كبير - أزرق'},
        'B096DJNNDS': {
            'item_title': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Buttoned Polo T-Shirt\n\n\n\n\n\n\n',
            'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B096DJNNDS.jpg',
            'item_url': 'https://www.amazon.eg/dp/B096DJNNDS/?language=en_AE', 'item_price': 'EGP 89.00',
            'item_uid': 'B096DJNNDS', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:47',
            'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
            'item_title_ar': '\n\n\n\n\n\n\n\nDolab Casual Solid Short Sleeves Buttoned Polo T-Shirt\n\n\n\n\n\n\n'},
        'B092312ZDR': {'item_title': '\n\n\n\n\n\n\n\nHero Mixed V Neck T-Shirt For Men\n\n\n\n\n\n\n, Select',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B092312ZDR.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B0924W2P9H/?language=en_AE',
                       'item_price': 'EGP 69.00 - EGP 98.00', 'item_uid': 'B092312ZDR', 'currency': 'EGP',
                       'date': '12-09-2021', 'time': '22:15:49', 'item_website': 'www.amazon.eg', 'tree': '',
                       'item_sizes': {'XL': 'found', 'XXL': 'found'},
                       'item_title_ar': '\n\n\n\n\n\n\n\nHero Mixed V Neck T-Shirt For Men\n\n\n\n\n\n\n'},
        'AM423MW0H656INAFAMZ': {'item_title': 'American Eagle Active Graphic T- Shirt -  Olive',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0H656INAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-active-graphic-t-shirt-olive-22104882.html',
                                'item_price': '220.00', 'item_uid': 'AM423MW0H656INAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Active Graphic T-Shirt - Olive'},
        'AM423MW0XF1QMNAFAMZ': {'item_title': 'American Eagle Ae Active Graphic T-Shirt - Blue',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0XF1QMNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-ae-active-graphic-t-shirt-blue-22492165.html',
                                'item_price': '120.00', 'item_uid': 'AM423MW0XF1QMNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Ae Active Graphic T-Shirt - Blue'},
        'AM423MW11L5A4NAFAMZ': {'item_title': 'American Eagle Slim Fit Oxford Button-Up Shirt - Pink',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW11L5A4NAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-slim-fit-oxford-button-up-shirt-pink-21423136.html',
                                'item_price': '340.00', 'item_uid': 'AM423MW11L5A4NAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Slim Fit Oxford Button-Up Shirt - Pink'},
        'AM423MW0M3VJWNAFAMZ': {'item_title': 'American Eagle Slim Flex Polo Shirt - Navy',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0M3VJWNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-slim-flex-polo-shirt-navy-21423173.html',
                                'item_price': '330.00', 'item_uid': 'AM423MW0M3VJWNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:48', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Slim Flex Polo Shirt - Navy'},
        'AM423MW1HPZRWNAFAMZ': {'item_title': 'American Eagle Striped Slim Fit Oxford Button-Up Shirt - Gray',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW1HPZRWNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-striped-slim-fit-oxford-button-up-shirt-gray-21423209.html',
                                'item_price': '340.00', 'item_uid': 'AM423MW1HPZRWNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:50', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Striped Slim Fit Oxford Button-Up Shirt - Gray'},
        'AM423MW0TQE1MNAFAMZ': {'item_title': 'American Eagle Active Graphic T- Shirt -  Black',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0TQE1MNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-active-graphic-t-shirt-black-22104994.html',
                                'item_price': '220.00', 'item_uid': 'AM423MW0TQE1MNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Active Graphic T-Shirt - Black'},
        'AM423MW1FVHHQNAFAMZ': {'item_title': 'American Eagle Super Soft Graphic T-Shirt - Berry',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW1FVHHQNAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-graphic-t-shirt-berry-22492178.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW1FVHHQNAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle تي-شورت سوبر سوفت مزين بطبعة'},
        'AM423MW02P2XANAFAMZ': {'item_title': 'American Eagle Super Soft Graphic T-Shirt - Pink',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW02P2XANAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-super-soft-graphic-t-shirt-pink-22492540.html',
                                'item_price': '160.00', 'item_uid': 'AM423MW02P2XANAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle تي-شورت سوبر سوفت مزين بطبعة'},
        'AM423MW0SLI1ONAFAMZ': {'item_title': 'American Eagle Pique Polo Shirt - White',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/AM423MW0SLI1ONAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/american-eagle-pique-polo-shirt-white-21423084.html',
                                'item_price': '330.00', 'item_uid': 'AM423MW0SLI1ONAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:48', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '',
                                'item_title_ar': 'American Eagle Pique Polo Shirt - White'},
        'N46930750V': {'item_title': 'Casual Denim Hooded Shirt Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46930750V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46930750V/p', 'item_price': '209',
                       'item_uid': 'N46930750V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص جينز كاجوال بغطاء للرأس أزرق'},
        'N40617993V': {'item_title': 'Side Pocket Short Sleeve Shirt Sky Blue Oxford',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40617993V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40617993V/p', 'item_price': '318.00',
                       'item_uid': 'N40617993V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بأكمام قصيرة وجيوب جانبية أزرق سماوي أكسفورد'},
        'N40618249V': {'item_title': 'Striped Long Sleeve Shirt Blue Stripe',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40618249V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40618249V/p', 'item_price': '447',
                       'item_uid': 'N40618249V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص مخطط بأكمام طويلة أزرق بنمط مخطط'},
        'N46936597V': {'item_title': 'Oversize Fit Pocket Shirt Light Khaki',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936597V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936597V/p', 'item_price': '239',
                       'item_uid': 'N46936597V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص كبير الحجم بجيب الكاكي الفاتح'},
        'N39963082V': {'item_title': 'Side Pocket Checkered Shirt Caviar Comfort Fit',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39963082V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39963082V/p', 'item_price': '452',
                       'item_uid': 'N39963082V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بنقشة مربعات وجيوب جانبية قماش كافيار بقصة مريحة'},
        'N39961021V': {'item_title': 'Bold Striped Shirt Sky Captain / Comfort',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961021V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961021V/p', 'item_price': '324',
                       'item_uid': 'N39961021V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص مخطط بخطوط عريضة سكاي كابتن/كومفوررت'},
        'N33407033V': {'item_title': 'Fedora Zebra Print Long Sleeve Shirt Peat',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33407033V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33407033V/p', 'item_price': '336',
                       'item_uid': 'N33407033V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص فيدورا بنقشة زيبرا بأكمام طويلة ِبيت'}, 'B098PQGKCL': {
        'item_title': '\n\n\n\n\n\n\n\nAndora Plaid Slim-Fit Long Sleeves Shirt for Men\n\n\n\n\n\n\n, Select',
        'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B098PQGKCL.jpg',
        'item_url': 'https://www.amazon.eg/dp/B08WJN6WVY/?language=en_AE', 'item_price': 'EGP 144.00',
        'item_uid': 'B098PQGKCL', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
        'item_website': 'www.amazon.eg', 'tree': '',
        'item_sizes': {'Large': 'found', 'X-Large': 'found', 'XX-Large': 'found'},
        'item_title_ar': '\n\n\n\n\n\n\n\nAndora Plaid Slim-Fit Long Sleeves Shirt for Men\n\n\n\n\n\n\n'},
        'B09846T6GP': {'item_title': "\n\n\n\n\n\n\n\nReebok Men's Solid Regular fit T-Shirt\n\n\n\n\n\n\n, Select",
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B09846T6GP.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B082QHG2TM/?language=en_AE',
                       'item_price': 'EGP 537.00 - EGP 711.00', 'item_uid': 'B09846T6GP', 'currency': 'EGP',
                       'date': '12-09-2021', 'time': '22:15:47', 'item_website': 'www.amazon.eg', 'tree': '',
                       'item_sizes': {'Small': 'found', 'Medium': 'found', 'Large': 'found', 'X-Large': 'found'},
                       'item_title_ar': "\n\n\n\n\n\n\n\nReebok Men's Solid Regular fit T-Shirt\n\n\n\n\n\n\n"},
        'N40618273V': {'item_title': 'Textured Collared Neck Shirt Grey',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40618273V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40618273V/p', 'item_price': '447',
                       'item_uid': 'N40618273V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'تيشيرت نسيجي برقبة مقببة رمادي'},
        'N39961071V': {'item_title': 'Flap Pocket Shirt Elmwood / Overshirt',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961071V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961071V/p', 'item_price': '582',
                       'item_uid': 'N39961071V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بجيب بقلاب إلموود/أوفرشيرت'},
        'N39962982V': {'item_title': 'Floral Print Slim Fit Shirt Dark Navy Slim Fit',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962982V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962982V/p', 'item_price': '530',
                       'item_uid': 'N39962982V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص قصّة ضيقة بطبعة زهور كحلي داكن بقصة ضيقة'},
        'N39961011V': {'item_title': 'Front Pocket Solid Shirt Dune / Comfort',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961011V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961011V/p', 'item_price': '622',
                       'item_uid': 'N39961011V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص سادة بجيب أمامي ديون/كومفورت'},
        'N44817393V': {'item_title': 'Stripes Long Sleeve Shirt With Collared Neck Multicolour',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N44817393V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N44817393V/p', 'item_price': '149.00',
                       'item_uid': 'N44817393V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص مخطط بأكمام طويلة ورقبة بياقة Multicolour'},
        'N46936264V': {'item_title': 'Basic Short Sleeve Shirt Pink',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936264V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936264V/p', 'item_price': '119',
                       'item_uid': 'N46936264V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بتصميم بسيط وبأكمام قصيرة وردي'},
        'N40010148V': {'item_title': 'Puff Sleeve Denim Shirt Black',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40010148V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40010148V/p', 'item_price': '434',
                       'item_uid': 'N40010148V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص جينز بأكمام منفوخة أسود'},
        'GE810MW1D2IOENAFAMZ': {'item_title': 'Casual -woman  Solid Shirt Cotton Light -white',
                                'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/GE810MW1D2IOENAFAMZ.jpg',
                                'item_url': 'https://www.jumia.com.eg/generic-casual-woman-solid-shirt-cotton-light-white-20781428.html',
                                'item_price': '136.00', 'item_uid': 'GE810MW1D2IOENAFAMZ', 'currency': 'EGP',
                                'date': '12-09-2021', 'time': '22:15:51', 'item_website': 'www.jumia.com.eg',
                                'tree': '', 'item_sizes': '', 'item_title_ar': 'شميز حريمى سادة -قطن لايت-ابيض'},
        'N33126392V': {'item_title': 'Linen Short Sleeve Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126392V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126392V/p', 'item_price': '608',
                       'item_uid': 'N33126392V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص من الكتان بأكمام قصيرة أبيض'},
        'N39961894V': {'item_title': 'Royal R001 RDD Shirt Safari',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961894V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961894V/p', 'item_price': '647',
                       'item_uid': 'N39961894V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص رويال R001 RDD سفاري'},
        'N39961889V': {'item_title': 'Royal R001 RDD Shirt Navy Blazer',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39961889V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39961889V/p', 'item_price': '647',
                       'item_uid': 'N39961889V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص رويال R001 RDD سترة كحلية'},
        'N40641316V': {'item_title': 'Banded Mandarin Neck Shirt Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40641316V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40641316V/p', 'item_price': '447',
                       'item_uid': 'N40641316V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بياقة ماندرين مدمجة أزرق'},
        'N44817468V': {'item_title': 'plain basic long sleeve shirt with collared neck Green',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N44817468V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N44817468V/p', 'item_price': '189',
                       'item_uid': 'N44817468V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص أساسي سادة بأكمام طويلة ورقبة بياقة أخضر'},
        'N38412334V': {'item_title': 'Curve Rull LS Oversized Shirt Nomad',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N38412334V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N38412334V/p', 'item_price': '672',
                       'item_uid': 'N38412334V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص كيرف بأكمام طويلة مطوية ومقاس كبير نوماد'},
        'N46936270V': {'item_title': 'Solid Pattern Short Sleeve Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936270V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936270V/p', 'item_price': '119',
                       'item_uid': 'N46936270V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص سادة بأكمام قصيرة أبيض'},
        'N39962388V': {'item_title': 'Colourblock Shirt Trekking Green Relaxed',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962388V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962388V/p', 'item_price': '428',
                       'item_uid': 'N39962388V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بنمط كتل ألوان تريكينج أخضر ريلاكسيد'},
        'N46936765V': {'item_title': 'Checkered Pattern Casual Shirt Red/Black',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936765V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936765V/p', 'item_price': '299',
                       'item_uid': 'N46936765V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'Checkered Pattern Casual Shirt أحمر/ أسود'},
        'N41399136V': {'item_title': 'Textured Long Sleeves Shirt Black',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N41399136V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N41399136V/p', 'item_price': '307',
                       'item_uid': 'N41399136V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص سميك بأكمام طويلة أسود'},
        'N39962373V': {'item_title': 'Large Front Pockets Shirt Navy Blazer Relaxed',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962373V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962373V/p', 'item_price': '428',
                       'item_uid': 'N39962373V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بجيوب أمامية كبيرة كحلي بليزر بقصة مريحة'},
        'N33126015V': {'item_title': 'Cuban Collared Short Sleeves Shirt Grey/White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126015V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126015V/p', 'item_price': '501',
                       'item_uid': 'N33126015V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بأكمام قصيرة وياقة كوبية رمادي/أبيض'},
        'N33126838V': {'item_title': 'Cotton Dobby Shirt Navy/White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126838V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126838V/p', 'item_price': '355',
                       'item_uid': 'N33126838V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:53',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص دوبي قطن كحلي/أبيض'},
        'B091KJWJZF': {'item_title': '\n\n\n\n\n\n\n\nSega Genesis\n\n\n\n\n\n\n',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/B091KJWJZF.jpg',
                       'item_url': 'https://www.amazon.eg/dp/B091KJWJZF/?language=en_AE', 'item_price': 'EGP 218.00',
                       'item_uid': 'B091KJWJZF', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:54',
                       'item_website': 'www.amazon.eg', 'tree': '', 'item_sizes': '',
                       'item_title_ar': '\n\n\n\n\n\n\n\nSega Genesis\n\n\n\n\n\n\n'},
        'N38469490V': {'item_title': 'Textured Long Sleeve Shirt in Blue Medium Blue Denim Cloud dancer',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N38469490V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N38469490V/p', 'item_price': '344',
                       'item_uid': 'N38469490V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص منسوج بأكمام طويلة بلون أزرق لون دنيم أزرق وسط كلاود دانسر'},
        'N46936259V': {'item_title': 'Solid Pattern Woven Short Sleeve Shirt Pink',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936259V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936259V/p', 'item_price': '119',
                       'item_uid': 'N46936259V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص محبوك بأكمام قصيرة وتصميم سادة وردي'},
        'N46936592V': {'item_title': 'Solid Pattern Pocket Detail Denim Shirt Light Khaki',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936592V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936592V/p', 'item_price': '239',
                       'item_uid': 'N46936592V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص جينز سادة بجيوب الكاكي الفاتح'},
        'N44472609V': {'item_title': 'Linen Blend Pants For Men Blue',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N44472609V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N44472609V/p', 'item_price': '299.00',
                       'item_uid': 'N44472609V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:49',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'بنطال مصنوع من مزيج الكتان للرجال أزرق'},
        'N46936289V': {'item_title': 'Solid Pattern Short Sleeve Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936289V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936289V/p', 'item_price': '229',
                       'item_uid': 'N46936289V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص سادة بأكمام قصيرة أبيض'},
        'N39963087V': {'item_title': 'Side Pocket Checkered Shirt Dress Blues Comfort Fit',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39963087V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39963087V/p', 'item_price': '452',
                       'item_uid': 'N39963087V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:50',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بنقشة مربعات وجيوب جانبية دريس بلوز بقصة مريحة'},
        'N46936219V': {'item_title': 'Casual Solid Pattern Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N46936219V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N46936219V/p', 'item_price': '199',
                       'item_uid': 'N46936219V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص كاجوال بتصميم سادة أبيض'},
        'N40010153V': {'item_title': 'Solid Pattern Lace Trim Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N40010153V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N40010153V/p', 'item_price': '434',
                       'item_uid': 'N40010153V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص سادة مزين بأشرطة دانتيل أبيض'},
        'N38995841V': {'item_title': 'Summer Brand Print Shirt Navy Blazer',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N38995841V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N38995841V/p', 'item_price': '495',
                       'item_uid': 'N38995841V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص صيفي بطبعة شعار العلامة التجارية سترة كحلية'},
        'N38995821V': {'item_title': 'Summer Brand Print Shirt White',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N38995821V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N38995821V/p', 'item_price': '629',
                       'item_uid': 'N38995821V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:52',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص صيفي بطبعة شعار العلامة التجارية أبيض'},
        'N33126387V': {'item_title': 'Linen Short Sleeves Shirt Navy',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126387V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126387V/p', 'item_price': '608',
                       'item_uid': 'N33126387V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص كتان بأكمام قصيرة كحلي'},
        'N38451342V': {'item_title': 'Damitta Textured Shirt Mahogany Rose',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N38451342V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N38451342V/p', 'item_price': '419.00',
                       'item_uid': 'N38451342V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص داميتا بنقشة بارزة ماهوجني روز'},
        'N33126382V': {'item_title': 'Short Sleeves Shirt Infinity',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N33126382V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N33126382V/p', 'item_price': '608',
                       'item_uid': 'N33126382V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'قميص بأكمام قصيرة إنفينيتي'},
        'N39962383V': {'item_title': 'Colourblock Stripe Shirt Red/Blue/Yellow',
                       'item_image': 'https://storage.googleapis.com/bright-lattice-260000.appspot.com/product_images/N39962383V.jpg',
                       'item_url': 'https://www.noon.com/egypt-en/N39962383V/p', 'item_price': '428',
                       'item_uid': 'N39962383V', 'currency': 'EGP', 'date': '12-09-2021', 'time': '22:15:51',
                       'item_website': 'www.noon.com', 'tree': '', 'item_sizes': '',
                       'item_title_ar': 'تيشيرت مخطط بنمط عدة ألوان أحمر / أزرق / أصفر'}}


class UploadDB:
    def __init__(self, json_data):
        self.json_items = json_data

    def db_connection(self):
        try:
            conn = mysql.connector.connect(user="admin", password="Api-0000",
                                           host="129.159.205.105", port=3306, database="main_schema")
        except mysql.connector.Error as err:
            if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
                print("Something is wrong with the user name or password")
            elif err.errno == errorcode.ER_BAD_DB_ERROR:
                print("Database does not exist")
            else:
                print(err)
        else:
            cursor = conn.cursor()

    def UID_Generator(self, unique_product_code):
        text_hash = blake2b(digest_size=2)
        text_hash.update(unique_product_code.encode("utf-8"))
        return f"A{text_hash.hexdigest()}{str(uuid.uuid4())[:4]}"

    def extract_json(self):
        query = "INSERT INTO products_eg (source_identifier_code, website_name, UIC, country, price_data, " \
                "product_category_en, product_category_ar, product_type_en, product_type_ar, search_key, " \
                "search_key_ar, title_en, title_ar, brand_en, brand_ar, item_specs_en, item_specs_ar, " \
                "images_url, product_direct_link_en, product_direct_link_ar, item_upc, sold_out, " \
                "rating,number_of_reviews, item_date) VALUES {}"
        items_list = []
        for item_id, item in self.json_items.items():
            price_dict = {
                item.get('currency'): {
                    f'{item.get("date")} {item.get("time")}': {
                        'date_time': f'{item.get("date")} {item.get("time")}',
                        'price': item.get('item_price'),
                        'currency': item.get('currency')
                    }
                }
            }

            item_list = [
                item_id,
                item.get('item_website'),
                self.UID_Generator(item_id),
                item.get('country'),
                json.dumps(price_dict),
                item.get('product_type'),
                item.get('product_type_ar'),
                item.get('product_type').split(' @ ')[-1],
                item.get('product_type_ar').split(' @ ')[-1],
                item.get('search_key'),
                '',

            ]

        print(items_list.append(item_list))
        return ''


ex = UploadDB(data).extract_json()


# h = blake2b(digest_size=2)
# tes = 'ramy'
# h.update(tes.encode("utf-8"))
#
#
# print(h.hexdigest() + str(uuid.uuid4())[:4])
